version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: lease-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lease_db
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    restart: always 